### ISSUE TITLE
How To: Recover/Recreate corrupted Pi-hole database

### ISSUE THREAD

**Issue by brigcam** [casperklein/homeassistant-addons#42]
**Add-on name**
Pi-hole

**Describe the feature you'd like**
Recover/Recreate corrupted Pi-hole database from the add-on interface

**Describe alternatives you've considered**
Recover/Recreate the database manually

**Additional context**
Hello, I've had my Pi-hole gravity.db corrupted twice on my Home Assistant instance, first time it recovered by itself just by rebooting the Pi, second time rebooting and also trying to restore a backup didn't work, so I had to do it manually by entering the command line inside the add on docker container, for anyone who may need it here's the procedure:

From a root terminal (ie [Advanced SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh))
`docker exec -it addon_0da538cf_pihole bash`

It should open a terminal within the Pi-hole add on. From there
`pihole -g -r recover`

or if it doesn't work
`pihole -g -r recreate`

and that should do the trick, now you can type
`exit`

to exit the add on command line.

I don't know if the name of the add-on is fixed or not, if the latter is true, do this to see its exact name
`docker ps`

Hope this helps someone and of course it'd be handy if there was an automated procedure to do this within the add on interface. Thanks again to the add on author for the great work!

**Comment by casperklein** [comment]
Hi,

thank you for bringing this up 👍 

> also trying to restore a backup didn't work

Then the backup probably already got a corrupted database.

> I don't know if the name of the add-on is fixed or not

The name is fixed.
`0da538cf` is a hash of the repository URL (`printf %s https://github.com/casperklein/homeassistant-addons | sha1sum | head -c8`)

Another way to fix a corrupted DB: If you are still able to access the web UI, you can create a backup using the _Teleporter_ (Settings - Teleporter). Or even better: you make a _Teleporter_ backup from time to time. Then uninstall the add-on and install it again. After that restore the settings via the _Teleporter_.

---

I also experienced a problem with a corrupted DB two times. From my observation, it happened after a gravity update - which runs once a week on sunday. However I wasn't able to reliable reproduce that error, which makes it hard to fix / report upstream to Pi-hole.

Instead of providing an easier way to reset the DB, I'd like to find and fix the root cause for the corruption.

**Comment by casperklein** [comment]
You had two typos in your post, the commands should have the `-r` option, instead of `-d`: `pihole -g -r recover`

I've fixed them.

**Comment by Hatton920** [comment]
> Hi,
> 
> thank you for bringing this up 👍
> 
> > also trying to restore a backup didn't work
> 
> Then the backup probably already got a corrupted database.
> 
> > I don't know if the name of the add-on is fixed or not
> 
> The name is fixed. `0da538cf` is a hash of the repository URL (`printf %s https://github.com/casperklein/homeassistant-addons | sha1sum | head -c8`)
> 
> Another way to fix a corrupted DB: If you are still able to access the web UI, you can create a backup using the _Teleporter_ (Settings - Teleporter). Or even better: you make a _Teleporter_ backup from time to time. Then uninstall the add-on and install it again. After that restore the settings via the _Teleporter_.
> 
> I also experienced a problem with a corrupted DB two times. From my observation, it happened after a gravity update - which runs once a week on sunday. However I wasn't able to reliable reproduce that error, which makes it hard to fix / report upstream to Pi-hole.
> 
> Instead of providing an easier way to reset the DB, I'd like to find and fix the root cause for the corruption.

I’ve also had database corruption which has always been on a Sunday. It’s very random but it’s happened about 3/4 times now. 

I did think maybe my home assistant backup routine was getting in the way of it but I’ve stopped it backing up on a Sunday and still happens.

**Comment by casperklein** [comment]
I think I’ve [found the cause](#43) of the database corruption that occurs on Sundays.

**Comment by Hatton920** [comment]
> I think I’ve [found the cause](https://github.com/casperklein/homeassistant-addons/issues/43) of the database corruption that occurs on Sundays.

Is this something you can fix or passed to the pihole team?
